### ISSUE TITLE
Django 1.6+

### ISSUE THREAD

**Issue by vartagg** [arteria/django-favicon-plus#1]
Will this package be available for newest versions of Django? What is the main problem that impedes this?

**Comment by walterrenner** [comment]
hi @vartagg,

I don't think there will be a problem installing this app with the newest django version since it is just one simple templatetag and a very basic model. But he haven't tried yet.

Maybe you can find the time and install this app with skipping the `django>=1.4.16,<1.5` requirements and report issues, if any.

(dont't forget to install [`django-compat`](https://github.com/arteria/django-compat) and [`Pillow`](https://github.com/python-pillow/Pillow) manually)

**Comment by bashu** [comment]
+1
